# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
safe: false

# Site settings
title: 未来ガジェット研究所
email: ini.universe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ONE FOR ALL
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://a1phazer0.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: A1phaZer0
hackerrank_username: inituniverse
deviantart_username: a1phazer0

# Build settings
markdown: kramdown

# separator between excerpt and rest of a post
excerpt_separator: <!--more-->

# categories
categories-list: [Algorithm,Compiler,Hacks,Write-ups,Network,Unix,Misc]

# pgaination
gems: [jekyll-paginate]
paginate : 10
paginate_path: /blog/page:num
